### ISSUE TITLE
Vertaisarvio

### ISSUE THREAD

**Issue by bensku** [ahaavisto/kastaaja#1]
Erittäin mielenkiintoinen projektin aihe! JavaFX 8 ja Java 11 epäyhteensopivuuden vuoksi en ikävä kyllä päässyt testaamaan sitä itse, joten kommenttini perustuvat vain reposto 28.2.2020 noin klo 21.30 haettuun koodiin.

Ensimmäisenä koodissa pistävät silmään käyttämäsi Javan standardikirjaston luokat <code>ArrayList</code> ja <code>HashMap</code>. Kumpaakaan näistä ei ole erityisen *vaikea* toteuttaa, etenkään jos ei lähde optimoimaan koodia. Silti, nyt on alle viikko aikaa jäljellä - suosittelen panostamaan omiin tietorakenteisiin eniten.

Ohjelma vaikuttaa olevan muuten aivan toimivassa kunnossa. Javadoc-kommentteja löytyy sen verran, ettei minun tarvinnut lukea varsinaista koodia ymmärtääkseni ohjelman ideaa. Myös muuttujien ja metodien nimeäminen on selkeää.

Kastaaja on toteutettu kokonaan kahteen luokkaan, mikä ei ole mielestäni hyvä idea. Tämän kokoisessa projektissa se ei vielä ole katastrofi, mutta ei se ole myöskään hyvä tapa. Ohjelman käyttämiä tietorakenteita voisi myös abstraktoida vähän kauemmas UIsta, vaikka omiin luokkiinsa. Samalla osan staattisista metodeista saisi siirrettyä ko. luokkiin, mikä selkeyttäisi projektin rakennetta.

Koodi on selkeää, mutta sen tyyli ei täysin vastaa suosituksia Javalle. Esimerkiksi <code>snake_case</code>a ei pitäisi käyttää juuri muualla kuin vakioissa (<code>SNAKE_CASE</code>). Ohjelman toimintaan tämä ei vaikuta, mutta kielen virallisten nimeämistapojen noudattaminen helpottaa muun koodin integrointia. Lisäksi se on hyvä tapa oppia, koska useamman henkilön projekteissa käytetään yleensä juuri niitä virallisia tyylisääntöjä.

**Comment by ahaavisto** [comment]
Kiitos kommenteista!
